# Generated by Django 5.0.1 on 2024-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_accountmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='is_activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
