# Generated by Django 5.0.1 on 2024-01-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_vaccine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='initial_dose',
            field=models.DateTimeField(max_length=50),
        ),
    ]
