# Generated by Django 5.0.1 on 2024-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines/uploads/'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='precautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
