# Generated by Django 5.0.1 on 2024-01-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_vaccine_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='precautions',
        ),
    ]
